In [37]:
import pickle
import numpy as np
import pandas as pd
train_x = pickle.load(open('train_2C_simulation_x.pkl','rb'))
train_y = pickle.load(open('train_y.pkl','rb'))

train_x_val = train_x.value

train_x_past = train_x.shift(periods=1, fill_value=0)
train_x_2past = train_x.shift(periods=2, fill_value=0)

#train_x_f = pd.concat([train_x,train_x_past,train_x_two])
train_x=pd.concat([train_x, train_x_past, train_x_2past], axis=1,names=["value","past","2past"])


In [38]:
from sklearn.utils import resample
train_x, train_y = resample(train_x,  train_y, random_state=0,replace=True,stratify=train_y)

In [39]:
#X_train_selected_transformed, X_test_selected_transformed, y_train_encoded, y_test_encoded=prepare_undersample_train_test(train_x, train_y)

In [40]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
train_x = mm_scaler.fit_transform(train_x)
#mm_scaler.transform(train_x)


In [41]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC
#clf = SVC(kernel='linear', 
#            class_weight='balanced', # penalize
#            probability=True,verbose=True)
clf = AdaBoostClassifier(n_estimators=5, random_state=0)

clf.fit(train_x, train_y)
clf.score(train_x, train_y)

0.9776864357017029

In [42]:
train_x

array([[0.        , 0.04722222, 0.63855422, ..., 0.62896316, 0.98264134,
        0.43575349],
       [0.        , 0.        , 0.3815261 , ..., 0.65649413, 0.9828766 ,
        0.64962511],
       [0.        , 0.63611111, 0.16064257, ..., 0.28577548, 0.96811995,
        0.60098324],
       ...,
       [0.        , 0.82222222, 0.65461847, ..., 0.60187939, 0.98879162,
        0.49300192],
       [0.        , 0.        , 0.26506024, ..., 0.83834385, 0.96283759,
        0.99749467],
       [0.00416667, 0.76666667, 0.36546185, ..., 0.64416242, 0.96404371,
        0.94280752]])

In [43]:
clf.feature_importances_

array([0., 0., 0., ..., 0., 0., 0.])

In [44]:
test_x = pickle.load(open('test_2C_simulation_x.pkl','rb'))
test_x_val=test_x.value

test_x_past = test_x.shift(periods=1, fill_value=0)
test_x_2past = test_x.shift(periods=2, fill_value=0)



#train_x_f = pd.concat([train_x,train_x_past,train_x_two])
test_x=pd.concat([test_x, test_x_past, test_x_2past], axis=1,names=["value","past","2past"])
mm_scaler.transform(test_x)
test_y = clf.predict(test_x.to_numpy())


In [45]:
test_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [46]:
test_x = pickle.load(open('test_94C_x.pkl','rb'))
test_x['pred'] = np.array(np.round(test_y).reshape(504)).astype(int)
test_x[['pred']].to_csv('test_94C_y_witek3.csv',header=False,sep=';')