In [26]:
import pickle
import numpy as np
import pandas as pd
train_x = pickle.load(open('train_2C_simulation_x.pkl','rb'))
train_y = pickle.load(open('train_y.pkl','rb'))
print(train_x.columns)

train_x_val = train_x.value

#train_x_past = train_x.shift(periods=1, fill_value=0)
#train_x_2past = train_x.shift(periods=2, fill_value=0)

#train_x_f = pd.concat([train_x,train_x_past,train_x_two])
#train_x=pd.concat([train_x, train_x_past, train_x_2past], axis=1,names=["value","past","2past"])
train_x=train_x[["value","353200272_Precipitation-sum-past-24-hrs",'353200272_Soil-temperature']]
",'00_030_015','00_024_016','00_024_017','00_024_045','00_024_046','00_024_047','00_024_048','00_024_049','00_024_049'"

Index(['value', '353200272_Wind-direction', '353200272_Air-temperature',
       '353200272_Soil-temperature', '253200080_Precipitation-sum-past-24-hrs',
       '353200272_Precipitation-sum-past-24-hrs',
       '253200080_Precipitation-sum-past-1-hrs',
       '353200272_Precipitation-sum-past-1-hrs',
       '253200080_Precipitation-sum-past-10-mts',
       '353200272_Precipitation-sum-past-10-mts',
       ...
       '00_030_45', '00_030_46', '00_030_47', '00_030_48', '00_030_49',
       '00_030_5', '00_030_6', '00_030_7', '00_030_8', '00_030_9'],
      dtype='object', length=564)


",'00_030_015','00_024_016','00_024_017','00_024_045','00_024_046','00_024_047','00_024_048','00_024_049','00_024_049'"

In [27]:
train_x

value  353200272_Precipitation-sum-past-24-hrs  \
timestamp                                                             
2019-06-14 23:00:00    0.0                                     29.2   
2019-06-14 16:00:00    0.0                                     29.2   
2019-06-14 08:00:00    0.0                                     29.2   
2019-06-14 13:00:00    0.0                                     29.2   
2019-06-14 22:00:00    0.0                                     29.2   
...                    ...                                      ...   
2019-08-31 19:00:00    0.0                                      0.0   
2019-08-31 20:00:00    0.0                                      0.0   
2019-08-31 21:00:00    0.0                                      0.0   
2019-08-31 22:00:00    0.0                                      0.0   
2019-08-31 23:00:00    0.0                                      0.0   

                     353200272_Soil-temperature  
timestamp                                        
2019-06-14 23:00:00                        14.6  
2019-06-14 16:00:00                        25.3  
2019-06-14 08:00:00                        20.2  
2019-06-14 13:00:00                        26.5  
2019-06-14 22:00:00                        15.9  
...                                         ...  
2019-08-31 19:00:00                        20.0  
2019-08-31 20:00:00                        18.2  
2019-08-31 21:00:00                        15.6  
2019-08-31 22:00:00                        15.1  
2019-08-31 23:00:00                        14.0  

[1703 rows x 3 columns]

In [28]:
from sklearn.utils import resample
train_x, train_y = resample(train_x,  train_y, random_state=13,replace=True) #,stratify=train_y

In [29]:
#X_train_selected_transformed, X_test_selected_transformed, y_train_encoded, y_test_encoded=prepare_undersample_train_test(train_x, train_y)

In [30]:
from sklearn import preprocessing
mm_scaler = preprocessing.MinMaxScaler()
train_x = mm_scaler.fit_transform(train_x)
#mm_scaler.transform(train_x)


In [51]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
#clf = SVC(kernel='linear', 
#            class_weight='balanced', # penalize
#            probability=True,verbose=True)
clf = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1,max_features=12),algorithm="SAMME",n_estimators= 420, random_state=10,learning_rate=1.85)

scores = cross_val_score(clf,train_x, train_y, cv=3)
print(scores)
clf.fit(train_x, train_y)
#clf.score(train_x, train_y)

[0.94366197 0.94190141 0.94003527]


AdaBoostClassifier(algorithm='SAMME',
                   base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=1,
                                                         max_features=None,
                                                         max_leaf_nodes=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                                         min_weight_fraction_leaf=0.0,
                                                         presort='deprecated',
                            

In [52]:
train_x

array([[0.        , 0.01771654, 0.24451411],
       [0.        , 0.03937008, 0.09404389],
       [0.        , 0.00590551, 0.06896552],
       ...,
       [0.        , 0.0019685 , 0.830721  ],
       [0.        , 0.1003937 , 0.52664577],
       [0.        , 0.03346457, 0.12852665]])

In [53]:
arr=clf.feature_importances_
idx = (-arr).argsort()[:15]
print(arr.shape)
print(idx)

(3,)
[1 2 0]


In [54]:
test_x = pickle.load(open('test_2C_simulation_x.pkl','rb'))
#test_x_val=test_x.value

#test_x_past = test_x.shift(periods=1, fill_value=0)
#test_x_2past = test_x.shift(periods=2, fill_value=0)



#train_x_f = pd.concat([train_x,train_x_past,train_x_two])
#test_x=pd.concat([test_x, test_x_past, test_x_2past], axis=1,names=["value","past","2past"])

test_x=test_x[["value","353200272_Precipitation-sum-past-24-hrs",'353200272_Soil-temperature']]
mm_scaler.transform(test_x)

array([[0.        , 0.00590551, 0.36363636],
       [0.        , 0.00590551, 0.37304075],
       [0.        , 0.00590551, 0.32601881],
       ...,
       [0.        , 0.        , 0.37931034],
       [0.        , 0.        , 0.26959248],
       [0.        , 0.        , 0.26332288]])

In [55]:

test_y = clf.predict(test_x.to_numpy())

In [57]:
test_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [78]:
test_x = pickle.load(open('test_94C_x.pkl','rb'))

test_x['pred'] = np.array(np.round(test_y).reshape(504)).astype(int)
test_x[['pred']].to_csv('test_94C_y_witek38.csv',header=False,sep=';')